
NUM_ACTIONS = 29
GENOME_LENGTH = NUM_ACTIONS
POPULATION_SIZE = 25
OFFSPRING_SIZE = 50
TOURNAMEN_SIZE = 3
MUTATION_PROBABILITY = 0.1
EVALUATION_IT = 50
NUM_GENERATIONS = 100
NUM_ISLANDS = 4
MIGRATION_INTERVAL = 10 
MIGRATION_SIZE = 5
ELITISM_SIZE = 5
EVALUATION_TYPE = "mixed" # mirror or mixed
LOAD_CHECKPOINT = True
STARTING_SPLIT = 5